version: '3.8'

services:
  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:13
    container_name: movilidad_db
    # Las credenciales se cargan desde el archivo .env para mayor seguridad
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # Mapea el puerto 5432 del contenedor al 5433 de tu máquina
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persiste los datos de la BD
    networks:
      - app_network

  # Servicio de la API (FastAPI)
  api:
    build: ./api # Construye la imagen a partir del Dockerfile en la carpeta /api
    container_name: movilidad_api
    ports:
      - "8000:8000"
    depends_on:
      - db # Se asegura que el servicio 'db' se inicie antes que la 'api'
    environment:
      # Usamos el nombre del servicio 'db' como host, Docker se encarga de la resolución
      DATABASE_HOST: db
    networks:
      - app_network

  # Servicio para ejecutar el Pipeline ETL
  pipeline:
    build: ./etl # Construye la imagen desde la carpeta /etl
    container_name: etl_runner
    command: ["python", "pipeline_etl.py"] # Este servicio ejecuta el pipeline y termina
    depends_on:
      - api # Se asegura que la API esté lista
    environment:
      # La API es accesible a través del nombre del servicio 'api'
      API_HOST: api
    volumes:
      # Mapea la carpeta de datos para que los CSV generados aparezcan en tu máquina local
      - ./data/raw:/app/data/raw
    networks:
      - app_network

  # Servicio para el Dashboard de Streamlit
  dashboard:
    build: ./dashboard # Construye la imagen desde la carpeta /dashboard
    container_name: dashboard_app
    command: ["streamlit", "run", "app.py"]
    ports:
      - "8501:8501"
    # La condición 'service_completed_successfully' es clave para la orquestación.
    # Garantiza que el dashboard solo se inicie si el pipeline tuvo éxito.
    depends_on:
      pipeline:
        condition: service_completed_successfully
    volumes:
      - ./data/raw:/app/data/raw # Necesita acceso al CSV que genera el pipeline
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: