version: '3.8'

services:
  base-datos:
    image: postgres:15-alpine
    container_name: postgres_movilidad_rm

    environment:
      POSTGRES_USER: estudiante
      POSTGRES_PASSWORD: estudiante_password
      POSTGRES_DB: movilidad_rm_db

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  pgdata: